const CHURCHES = [
  "Sem Igreja",
  "Ad Brás Osasco 1 de Maio",
  "Ad Brás Osasco Açucara",
  "Ad Brás Osasco Bandeiras",
  "Ad Brás Osasco Bonança",
  "Ad Brás Osasco Conceição",
  "Ad Brás Osasco Conj. Metalúrgicos",
  "Ad Brás Osasco Corrego Rico",
  "Ad Brás Osasco Flamenguinho",
  "Ad Brás Osasco Flor da Primavera",
  "Ad Brás Osasco Guanabara",
  "Ad Brás Osasco Helena Maria I",
  "Ad Brás Osasco Helena Maria II",
  "Ad Brás Osasco Jandaia",
  "Ad Brás Osasco Jd D'Abril SP",
  "Ad Brás Osasco Jd D'Abril Osasco",
  "Ad Brás Osasco Joelma",
  "Ad Brás Osasco Jussara",
  "Ad Brás Osasco Munhoz Junior",
  "Ad Brás Osasco Mutinga I",
  "Ad Brás Osasco Mutinga II",
  "Ad Brás Osasco Mutinga Ômega",
  "Ad Brás Osasco Novo Horizonte",
  "Ad Brás Osasco Novo Osasco",
  "Ad Brás Osasco Padroeira II",
  "Ad Brás Osasco Parque Imperial I",
  "Ad Brás Osasco Parque Imperial II",
  "Ad Brás Osasco Piratininga",
  "Ad Brás Osasco Portela",
  "Ad Brás Osasco Presidente Altino",
  "Ad Brás Osasco Quitaúna",
  "Ad Brás Osasco Recanto das Rosas 1",
  "Ad Brás Osasco Samambaia",
  "Ad Brás Osasco Santa Maria",
  "Ad Brás Osasco Santo Antonio",
  "Ad Brás Osasco Sede",
  "Ad Brás Osasco São João da Bela Vista",
  "Ad Brás Osasco São Vitor",
  "Ad Brás Osasco Teresa",
  "Ad Brás Osasco Três Montanhas",
  "Ad Brás Osasco Vila Dirce",
  "Ad Brás Osasco Vila dos Andrades",
  "Ad Brás Osasco Vila Menck",
  "Ad Brás Osasco Vila Simões",
  "Ad Brás Osasco Ypê",
];

const MESES = [
  'Janeiro','Fevereiro','Março','Abril','Maio','Junho',
  'Julho','Agosto','Setembro','Outubro','Novembro','Dezembro',
];

const DASH_COLORS = [
  '#4F81BD','#C0504D','#9BBB59','#8064A2','#4BACC6',
  '#F79646','#2C4770','#7B3F3F','#5A6E3C','#5B3F7A',
];
